const express = require('express');
const router = express.Router();
const { verifyToken } = require('../../middleware/superAdmin/auth.middleware.js');

const authRoutes = require('./auth.routes.js');
const categoryRoutes = require('./category.routes.js');
const choreiMessageRoutes = require('./choreiMessage.routes.js');
const cityRoutes = require('./city.routes.js');
const corporatePricePolicyRoutes = require('./corporatePricePolicy.routes.js');
const currencyMasterRoutes = require('./currencyMaster.routes.js');
const departmentRoutes = require('./department.routes.js');
const designationRoutes = require('./designation.routes.js');
const emergencyResponseRoutes = require('./emergencyResponse.routes.js');
const employeeRoutes = require('./employee.routes.js');
const eventRoutes = require('./event.routes.js');
const floorRoutes = require('./floor.routes.js');
const groupRoutes = require('./group.routes.js');
const holidayRoutes = require('./holiday.routes.js');
const homeRoutes = require('./home.routes.js');
const locationRoutes = require('./location.routes.js');
const loginDetailRoutes = require('./loginDetail.routes.js');
const messageRoutes = require('./message.routes.js');
const newsRoutes = require('./news.routes.js');
const noticeRoutes = require('./notice.routes.js');
const photoGalleryRoutes = require('./photoGallery.routes.js');
const policyRoutes = require('./policy.routes.js');
const popupImageRoutes = require('./popupImage.routes.js');
const priorityRoutes = require('./priority.routes.js');
const productRoutes = require('./product.routes.js');
const quoteRoutes = require('./quote.routes.js');
const roleRoutes = require('./role.routes.js');
const roomRoutes = require('./room.routes.js');
const salesPricePolicyRoutes = require('./salesPricePolicy.routes.js');
const sliderImageRoutes = require('./sliderImage.routes.js');
const ticketRoutes = require('./ticket.routes.js');
const unitRoutes = require('./unit.routes.js');
const zoneRoutes = require('./zone.routes.js');

// Middleware
router.use(verifyToken);

// Routes
router.use('/auth', authRoutes);
router.use('/categories', categoryRoutes);
router.use('/chorei-messages', choreiMessageRoutes);
router.use('/cities', cityRoutes);
router.use('/corporate-price-policies', corporatePricePolicyRoutes);
router.use('/currencies', currencyMasterRoutes);
router.use('/departments', departmentRoutes);
router.use('/designations', designationRoutes);
router.use('/emergency-response', emergencyResponseRoutes);
router.use('/employees', employeeRoutes);
router.use('/events', eventRoutes);
router.use('/floors', floorRoutes);
router.use('/groups', groupRoutes);
router.use('/holidays', holidayRoutes);
router.use('/home', homeRoutes);
router.use('/locations', locationRoutes);
router.use('/login-details', loginDetailRoutes);
router.use('/messages', messageRoutes);
router.use('/news', newsRoutes);
router.use('/notices', noticeRoutes);
router.use('/photo-galleries', photoGalleryRoutes);
router.use('/policies', policyRoutes);
router.use('/popup-images', popupImageRoutes);
router.use('/priorities', priorityRoutes);
router.use('/products', productRoutes);
router.use('/quotes', quoteRoutes);
router.use('/roles', roleRoutes);
router.use('/rooms', roomRoutes);
router.use('/sales-price-policies', salesPricePolicyRoutes);
router.use('/slider-images', sliderImageRoutes);
router.use('/tickets', ticketRoutes);
router.use('/units', unitRoutes);
router.use('/zones', zoneRoutes);

module.exports = router;
